/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author USER
 */
public class Latihan6 extends javax.swing.JFrame {

    /**
     * Creates new form Latihan6
     */
    public Latihan6() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label = new javax.swing.JLabel();
        HB1 = new javax.swing.JTextField();
        h1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Proses = new javax.swing.JButton();
        HB2 = new javax.swing.JTextField();
        HB3 = new javax.swing.JTextField();
        Diskon = new javax.swing.JTextField();
        h2 = new javax.swing.JLabel();
        h3 = new javax.swing.JLabel();
        dd = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Hasil = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        label.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        label.setText("Pembayaran");
        getContentPane().add(label);
        label.setBounds(220, 30, 90, 20);

        HB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HB1ActionPerformed(evt);
            }
        });
        getContentPane().add(HB1);
        HB1.setBounds(200, 80, 130, 30);

        h1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        h1.setText("Harga Barang 1");
        getContentPane().add(h1);
        h1.setBounds(70, 84, 90, 20);

        jPanel1.setBackground(new java.awt.Color(153, 204, 0));
        jPanel1.setLayout(null);

        Proses.setText("Proses");
        Proses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProsesActionPerformed(evt);
            }
        });
        jPanel1.add(Proses);
        Proses.setBounds(200, 250, 73, 23);
        jPanel1.add(HB2);
        HB2.setBounds(200, 120, 130, 30);
        jPanel1.add(HB3);
        HB3.setBounds(200, 160, 130, 30);
        jPanel1.add(Diskon);
        Diskon.setBounds(200, 200, 130, 30);

        h2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        h2.setText("Harga Barang 2");
        jPanel1.add(h2);
        h2.setBounds(70, 130, 90, 20);

        h3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        h3.setText("Harga Barang 3");
        jPanel1.add(h3);
        h3.setBounds(70, 170, 90, 20);

        dd.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        dd.setText("Diskon");
        dd.setToolTipText("");
        jPanel1.add(dd);
        dd.setBounds(70, 210, 60, 20);

        Hasil.setColumns(20);
        Hasil.setRows(5);
        jScrollPane1.setViewportView(Hasil);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(150, 280, 260, 130);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 510, 430);

        setBounds(0, 0, 528, 468);
    }// </editor-fold>//GEN-END:initComponents

    private void HB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HB1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HB1ActionPerformed

    private void ProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProsesActionPerformed
        int barang1 = Integer.parseInt(HB1.getText());
        int barang2 = Integer.parseInt(HB2.getText());
        int barang3 = Integer.parseInt(HB3.getText());
        int totalharga = barang1+barang2+barang3;
        int diskon = Integer.parseInt(Diskon.getText());
        
        int totalbayar = totalharga-(totalharga*diskon/100);
        
        Hasil.setText("Harga Barang 1 :"+barang1+ "\n" + "Harga Barang 2 :" +
                barang2+ "\n" + "Harga Barang 3 :" +barang3+ "\n" + "Diskon Anda :"
                +diskon+"\n"+"Total Harga :"+totalharga+"\n"+"Total bayar :"+totalbayar);
        
// TODO add your handling code here:
    }//GEN-LAST:event_ProsesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Latihan6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Latihan6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Latihan6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Latihan6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Latihan6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Diskon;
    private javax.swing.JTextField HB1;
    private javax.swing.JTextField HB2;
    private javax.swing.JTextField HB3;
    private javax.swing.JTextArea Hasil;
    private javax.swing.JButton Proses;
    private javax.swing.JLabel dd;
    private javax.swing.JLabel h1;
    private javax.swing.JLabel h2;
    private javax.swing.JLabel h3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label;
    // End of variables declaration//GEN-END:variables
}
